### ISSUE TITLE
Cant inject dll Win8 x64

### ISSUE THREAD

**Issue by sasharumega** [AdvDebug/MineRootkit#3]
While i injecting dll i have message "error while injecting"

i tried run x86 and x64 binaries

**Comment by AdvDebug** [comment]
make sure to run the rootkit program as x64 for x64 programs and same with x86 and make sure that MineRootkit have access to that process you specified and also make sure that the hooking library (MineRootkitHooking.dll) are present on the current path of the application and if that didn't work then get the last error code using Marshal.GetLastWin32Error() and send it here.

**Comment by AdvDebug** [comment]
No Response

**Comment by sasharumega** [comment]
hello! i dont understand problem but while i injected dll with ProcessHacker, it works!

**Comment by AdvDebug** [comment]
ok good
